### ISSUE TITLE
Failure to compile the solvers

### ISSUE THREAD

**Issue by Delinzzzzz** [ParticulateFlow/CFDEMcoupling-PFM#4]
Hi all,

I used "cfdemCompCFDEMall" command to compile the CFDEMcoupling-PFM, which is different from CFDEMcoupling-PUBLIC-5.x. I also had changed the name from "CFDEMcoupling-PFM" to "CFDEMcoupling-PUBLIC-5.x". But I failed to compile it and there was nothing new in home/CFDEM/CFDEMcoupling-PUBLIC-5.x/platforms/linux64GccDPInt32Opt/bin.
I'm new to use Linux/ubuntu so I'm not sure if I compiled it in the right way. Can anyone give me some suggestions?

Kind regards,
Delin.

**Comment by danielque** [comment]
Installation instructions can be found in the CFDEMcoupling docs. You can download an html version from the release page:
https://github.com/ParticulateFlow/CFDEMcoupling-PFM/releases
Note that CFDEMcoupling-PFM should be used together with LIGGGHTS-PFM since the interface is slightly different from the PUBLIC version. The log files in the etc/log sub-folder should provide more information on what might have gone wrong during compilation.
